[package]
name = "gyroflow-core"
version = "1.5.0"
authors = ["Adrian <adrian.eddy@gmail.com>", "Elvin Chen"]
edition = "2021"

[lib]
name = "gyroflow_core"
path = "lib.rs"

[dependencies]
#telemetry-parser = { path = "../../../telemetry-parser" }
telemetry-parser = { git = "https://github.com/AdrianEddy/telemetry-parser.git", rev = "26aec61" }
#ahrs = { version = "0.5.0", features = ["field_access"] }
ahrs = { git = "https://github.com/jmagnuson/ahrs-rs.git", rev = "bf7b41d", features = ["field_access"] }


#rs-sync = { path = "../../../rs-sync" }
rs-sync = { git = "https://github.com/gyroflow/rs-sync.git", rev = "eaabbc3" }

mimalloc = { version = "0.1.34", default-features = false }
nalgebra = { version = "0.32", features = ["serde-serialize"] }
rayon = "1.7"
biquad = "0.4.2"
fastrand = "1.9.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
bincode = "1.3.3"
serde = "1.0.152"
serde_json = "1.0.94"
crc32fast = "1.3.2"
byteorder = "1.4.3"
line_drawing = "1.0.0"
rand = "0.8.5"
time = { version = "0.3.20", features = ["local-offset"] }
itertools = "0.10.5"
num = "0.4.0"
base91 = "0.1.0"
bitflags = "1.3.2"
enum_delegate = "0.2.0"
simple-easing = "1.0.1"
half = "2.2.1"
lru = "0.10"

dyn-clone = "1.0.11"

akaze = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "d8ac7d3" }
eight-point = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "d8ac7d3" }
cv-pinhole = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "d8ac7d3" }
cv-core = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "d8ac7d3" }
sample-consensus = "1.0.2"
arrsac = "0.10.0"
rand_xoshiro = "0.6.0"
image = "0.23"
space = { version = "0.17", features = ["alloc"] }
bitarray = { version = "0.9", features = ["space"] }
enterpolation = "0.2.0"
libloading = "0.7"
libc = "0.2"

opencv = { version = "0.77", optional = true }

wgpu       = { git = "https://github.com/AdrianEddy/wgpu.git", branch = "buffer_from_raw" }
wgpu-hal   = { git = "https://github.com/AdrianEddy/wgpu.git", branch = "buffer_from_raw" }
wgpu-types = { git = "https://github.com/AdrianEddy/wgpu.git", branch = "buffer_from_raw" }
bytemuck = "1.13.1"
ash = "0.37.2"

pollster = "0.3.0"
futures-intrusive = "0.5.0"
flate2 = "1.0.25"
walkdir = "2.3.2"

log = "0.4.17"

ocl = { version = "0.19.4", optional = true, git = "https://github.com/cogciprocate/ocl" }
ocl-interop = { version = "0.1.5", optional = true, git = "https://github.com/cogciprocate/ocl" }

rustfft = "6.1.0"

include_dir = { version = "0.7.3", features = ["glob"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.metal]
version = "0.24.0"
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.foreign-types]
version = "0.3.2"
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.objc-foundation]
version = "0.1.1"
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.core-foundation-sys]
version = "0.8.3"
[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.44.0"
features = [ "Win32_System_Com", "Win32_System_Console", "Win32_System_SystemServices", "Win32_UI_Shell", "Win32_Foundation",
             "Win32_Graphics_Dwm", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_Dxgi",
             "Win32_Security", "Win32_Security_Authorization", "Win32_System_WindowsProgramming", "Win32_System_Threading", "Win32_System_Registry" ]
[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = ["profileapi", "libloaderapi", "windef", "winuser", "dcomp"]
[target.'cfg(target_os = "windows")'.dependencies.d3d12]
version = "0.6.0"
git = "https://github.com/gfx-rs/d3d12-rs"
rev = "b940b1d71"
features = ["libloading"]

[features]
default = []
use-opencl = ["ocl", "ocl-interop"]
use-opencv = ["opencv"]
bundle-lens-profiles = []

[profile.deploy]
inherits = "release"
lto = true
codegen-units = 1
