name: Release

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets: [
          {
            os: ubuntu-latest,
            target: x86_64-unknown-linux-gnu,
            target2: x86_64-unknown-linux-gnu,
            cross: false,
            name: linux64,
            ext: "",
            vcpkg: "x64-linux-release",
            vcpkg2: "x64-linux-release",
            ffmpeg_url: "",
            ffmpeg_name: "ffmpeg-5.1-linux-clang-gpl-lite"
          },
          {
            os: macos-latest,
            target: x86_64-apple-darwin,
            target2: aarch64-apple-darwin,
            cross: false,
            name: mac-universal,
            ext: "",
            vcpkg: "x64-osx-release",
            vcpkg2: "arm64-osx",
            ffmpeg_url: "",
            ffmpeg_name: "ffmpeg-5.1-macOS-gpl-lite"
          },
          {
            os: windows-2022,
            target: x86_64-pc-windows-msvc,
            target2: x86_64-pc-windows-msvc,
            cross: false,
            name: windows64,
            ext: ".exe",
            vcpkg: "x64-windows-release",
            vcpkg2: "x64-windows-release",
            ffmpeg_url: "https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-5.1-windows-desktop-vs2022-gpl-lite.7z/download",
            ffmpeg_name: "ffmpeg-5.1-windows-desktop-vs2022-gpl-lite"
          }
      ]
    runs-on: ${{ matrix.targets.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.targets.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: gf9

      - name: Dependencies cache
        id: extcache
        uses: actions/cache@v3
        with:
          path: '${{ github.workspace }}/ext/'
          key: ${{ runner.os }}-gf-ext-3

      - name: Add rust target
        run: rustup target add ${{ matrix.targets.target2 }}

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true

      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/ext/vcpkg'
          vcpkgGitCommitId: 42cc830d874f8e24eb4eb05bd5bb28496e3d498c
          doNotCache: true

      # Download and install OpenCV
      - name: Install OpenCV and curl
        if: ${{ matrix.targets.os != 'ubuntu-latest' && steps.extcache.outputs.cache-hit != 'true' }}
        run: |
          vcpkg install "opencv4[core]:${{ matrix.targets.vcpkg }}"
          vcpkg install "opencv4[core]:${{ matrix.targets.vcpkg2 }}"
          vcpkg install "curl[core]:${{ matrix.targets.vcpkg }}"
          vcpkg install "opencl:${{ matrix.targets.vcpkg }}"

      # Download and install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.4.0
          dir: ${{ github.workspace }}/ext/
          cached: ${{ steps.extcache.outputs.cache-hit }}

      # Install LLVM
      - name: Install LLVM and Clang
        if: ${{ matrix.targets.os == 'windows-2022' }}
        uses: KyleMayes/install-llvm-action@v1.5.0
        with:
          version: "13.0"
          directory: ${{ github.workspace }}/ext/llvm
          cached: ${{ steps.extcache.outputs.cache-hit }}
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: ${{ matrix.targets.os == 'windows-2022' }}

      # Download ffmpeg
      - name: Download ffmpeg
        if: ${{ matrix.targets.os == 'windows-2022' && steps.extcache.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ github.workspace }}/ext/
          curl -L ${{ matrix.targets.ffmpeg_url }} -o ffmpeg.7z
          7z x ffmpeg.7z

      - name: Install dependencies Mac
        if: ${{ matrix.targets.os == 'macos-latest' }}
        run: |
          cd ${{ github.workspace }}/ext
          chmod +x install-deps-mac.sh
          ./install-deps-mac.sh CI

      - name: Install dependencies Linux
        if: ${{ matrix.targets.os == 'ubuntu-latest' }}
        env:
          PROJECT_DIR: ${{ github.workspace }}
          QT_DIR: ${{ env.Qt6_DIR }}
        run: |
          chmod +x ${{ github.workspace }}/ext/install-deps-linux.sh
          chmod +x ${{ github.workspace }}/_deployment/deploy-linux.sh
          ${{ github.workspace }}/_deployment/deploy-linux.sh build-docker

      - name: Build Gyroflow
        if: ${{ matrix.targets.os == 'windows-2022' }}
        env:
          CARGO_TARGET_DIR: ./target
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
          OPENCV_LINK_LIBS: opencv_core4,opencv_calib3d4,opencv_features2d4,opencv_imgproc4,opencv_video4,opencv_flann4,opencv_imgcodecs4
          OPENCV_LINK_PATHS: ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/lib
          OPENCV_INCLUDE_PATHS: ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/include
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.targets.cross }}
          command: build
          args: --target ${{ matrix.targets.target }} --profile deploy

      - name: Install Mac certificate
        if: ${{ matrix.targets.os == 'macos-latest' }}
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Build and deploy Mac
        if: ${{ matrix.targets.os == 'macos-latest' }}
        env:
          PROJECT_DIR: ${{ github.workspace }}
          QT_DIR: ${{ env.Qt6_DIR }}
          OPENCV_DIR: ${{ github.workspace }}/ext/vcpkg/installed/
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
          SIGNING_FINGERPRINT: ${{ secrets.MACOS_CERTIFICATE_FINGERPRINT }}
        run: |
          chmod +x ${{ github.workspace }}/_deployment/deploy-macos.sh
          ${{ github.workspace }}/_deployment/deploy-macos.sh deploy-universal

      - name: Notarize and staple release build
        if: ${{ matrix.targets.os == 'macos-latest' }}
        run: |
          npx notarize-cli --file ${{ github.workspace }}/_deployment/_binaries/Gyroflow-mac-universal.dmg --bundle-id xyz.gyroflow --asc-provider="${{ secrets.MACOS_TEAM }}" --username="${{ secrets.MACOS_ACCOUNT_USER }}" --password="${{ secrets.MACOS_ACCOUNT_PASS }}"
          xcrun stapler staple --verbose ${{ github.workspace }}/_deployment/_binaries/Gyroflow-mac-universal.dmg

      - name: Copy dist Windows
        if: ${{ matrix.targets.os == 'windows-2022' }}
        env:
          FFMPEG_DIR: ${{ github.workspace }}/ext/${{ matrix.targets.ffmpeg_name }}
        run: |
          ${{ github.workspace }}/_deployment/deploy-windows.bat ${{ github.workspace }} ${{ env.Qt6_DIR }} ${{ github.workspace }}/ext/vcpkg/installed/${{ matrix.targets.vcpkg }}/bin ${{ github.workspace }}/target/${{ matrix.targets.target }}/deploy
          cd ${{ github.workspace }}/_deployment/_binaries/win64/
          7z a ../Gyroflow-${{ matrix.targets.name }}.zip *

      - name: Save Binaries
        uses: actions/upload-artifact@v3
        with:
          name: gyroflow
          path: _deployment/_binaries/*.*

  github_release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: gyroflow

      - run: ls -l

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: ./*
